### PR TITLE
capitalizing cell type names during assignment

### PR DESCRIPTION
**Pull request by ivichadriana**
Very small changes made to these files, just to capitalize the cell types according to paper's comments.

-  EXP2_pseudos_pbm.ipynb: deleted unnecesary plots that showed redundant gene expression differences per cell type, not needed.
-  validation_processing.py: added one function to capitalize 
- Other notebooks: added a couple of lines to capitalize cell types using the function above.

### CODE REVIEW

**Review by nrosed — APPROVED** [review]
Looks good, some small suggestions / questions.

**Comment by ivichadriana** [comment]
<p>the parameters cell is parametrized through papermill, so i gotta do it after that cell so it works through papermill</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989109'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>removed, it was for something else.</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989132'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>the parameters cell is parametrized through papermill, so i gotta do it after that cell so it works through papermill</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989077'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>nice catch</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989153'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>ah, older version of the notebook. good catch.</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989213'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>same thing, parameters are set in papermill in this cell. the os.getcwd comes after</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989274'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>ah i should have done that. once i'm adressing reviewer comments i'll add that.</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989294'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>i hypothesize it's the cytoplasmic RNA vs. only nuclear that's dirivng the difference. along with dissociation responses. but cant know for sure</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989460'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>not gonna use it but good to know</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/5/discussion/#comment-2047989480'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
comments addressed, merging PR

**Pull request merged**
