### PR TITLE
changed plot color scheme, added gene ontology analysis results and plots, capitalized cell types, added license

### PR DESCRIPTION
**Pull request by ivichadriana**
Looks like a lot but it's small changes. 
Addressing comments from paper draft. needed to capitalize the cell types in the notebooks, and change the coloring of some plots. Added analysis of gene ontology and the spreadsheets from gene onotology analysis to results folder. Added license file too. 

- LICENSE: just added the typical license file.
- results/EXP4/* : just added the spreadsheets from gene ontology analysis.
- evaluation_experiments/EXP1_eval.ipynb: small changes for plots coloring, cell types capitalized.
- evaluation_experiments/EXP3_bayesprism_eval.ipynb: small changes for plots coloring, cell types capitalized.
- evaluation_experiments/EXP3_cibersort_eval.ipynb: small changes for plots coloring, cell types capitalized.
- evaluation_experiments/EXP3_eval.ipynb: small changes for plots coloring, cell types capitalized.
- evaluation_experiments/EXP4_eval.ipynb: changed colors and order of samples so they’re according to origin site. Also added the plotting for the GO analysis of PCA and NMF components. 
- functions/validation_processing.py: added function for NNLS of HGSOC samples that used to be within the notebook its intended for.

### CODE REVIEW

**Comment by nrosed** [comment]
looks good -- some plots changed, I flagged them just in case you didn't intend them to change. 

Also -- for GOrilla did you use the entire ranked gene list? just double checking

**Review by nrosed — APPROVED** [review]

**Comment by ivichadriana** [comment]
<p>yeah the filtering is done before in the preprocessing now, makes things easier to keep up with. those cell types are just the ones with like 2 or 3 cells.</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/6/discussion/#comment-2065283727'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>the parameters  used to be set as "random proportioned pseudobulk with noise", now showing the realistic proportions with no noise, so things changed. it's tricky with these notebooks since they're parametrized elsewhere, so the results would vary you know.</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/6/discussion/#comment-2065283823'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>yeah, this is  as expected though (random vs. realistic props)</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/6/discussion/#comment-2065283804'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>yeah diff parameters (diff proportion types and noise vs. no noise). i ran it with the other parameters but i am not exporting the resulting notebooks into github. this just happened to be the last set of parameters i ran so its saved as such.</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/6/discussion/#comment-2065283784'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>yeah, realistic proportions have a lot more preadipocytes so it chanegs the most. as expected.</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/6/discussion/#comment-2065283761'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>yeah, it's interesting that visually they look similar.</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/6/discussion/#comment-2065283867'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>yeah, i redid the statistical tests a bunch of times and got the same. and i guess they're deceiving visually</p>

---

 <a href='https://app.reviewnb.com/greenelab/pred_missing_celltypes/pull/6/discussion/#comment-2065283890'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ivichadriana** [comment]
<p>yes for ROrilla, i did the entire ranked gene list, then exporting the entire list of statistically significant paths. for the plots i picked the top 30 most significant paths only (just to show, otherwise it gets crazy big)</p>

**Comment by ivichadriana** [comment]
most comments where due to differences in parameters (random vs. realistic pseudobulks with noise vs. no noise).

**Pull request merged**
